# Generated by Django 3.2.3 on 2021-05-23 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='shoppingMall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('icon', models.URLField()),
                ('logo', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(default=0)),
                ('shipping', models.PositiveIntegerField(default=0)),
                ('url', models.URLField()),
                ('item_no', models.CharField(blank=True, max_length=100, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_purchased', models.BooleanField(default=False)),
                ('is_shared', models.BooleanField(default=False)),
                ('mall', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zzim.shoppingmall')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
